name: avocadoguard
description: Application AgroSafe - Diagnostic végétal et surveillance IoT

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.0 # pour accéder au cloud/base de données de Firebase
  csv: ^7.2.0 # pour pouvoir exporter au format .csv
  firebase_auth: ^5.0.0 # pour accéder à la fonctionnalité Authentification de Firebase
  firebase_core: ^3.0.0 # pour accéder au projet Firebase
  firebase_database: ^11.3.10 # pour accéder à la base de donnée Firebase Realtime
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^6.0.1 # pour le fichier .env
  flutter_local_notifications: ^21.0.0 # pour les langues
  google_fonts: ^6.1.0 # pour les polices
  intl: any
  path_provider: ^2.1.2
  primer_progress_bar: ^0.4.0
  share_plus: ^13.1.0
  shared_preferences: ^2.0.0
  web: ^1.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets: 
    - .env
  generate: true
  uses-material-design: true